import 'package:flutter/material.dart';

// credit https://www.spicingyourlife.com/?s=assamee
import './models/category.dart';
import './models/meal.dart';

const DUMMY_INDIAN_CATEGORIES = [
  
  
  Category(
    id: 'Kerala',
    title: 'Kerala',
    color: Colors.red,
  ),
  Category(
    id: 'Tamilnadu',
    title: 'Tamilnadu',
    color: Colors.blueAccent,
  ),
 
 Category(
    id: 'Odisha',
    title: 'Odisha',
    color: Colors.orange,
  ),
  Category(
    id: 'Bengali',
    title: 'Bengali',
    color: Colors.green,
  ),
   Category(
    id: 'North Indian',
    title: 'North Indian',
    color: Colors.purple,
  ),
  Category(
    id: 'Marathi',
    title: 'Marathi',
    color: Colors.pinkAccent,
  ),
  Category(
    id: 'Rajasthan',
    title: 'Rajasthan',
    color: Colors.yellow,
  ),
];
const DUMMY_INDIAN_MEALS = [
  Meal(
    id: 'm1',
    categories: [
      'North Indian',
      
    ],
    title: 'Papdi Bada Dahi Chaat',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://www.spicingyourlife.com/wp-content/uploads/2021/04/Assembling-Papdi-Bada-Dahi-Chaat-2-1024x1024.jpg',
    duration: 35,
    ingredients: [
      '2 cups All-Purpose Flour',
      '2 tbsp Ghee',
      '1 tsp Cumin Seeds',
      'Water as required to knead',
      'Cooking Oil for deep frying',
      '1 cup Curds / Yogurt thick',
      'Sugar as required to make the curds sweet.',
      'Pudina Chutney',
      'Imli Sonth Chutney',
      'Kala Namak',
      'Chat Masala',
    ],
    steps: [
      'In a bowl, take the flour along with ghee and cumin seeds.',
      'Mix well and slowly add warm water to the flour and knead to a stiff dough.',
      'Divide the dough into 4 to 5 balls. Dust well and roll out into 6inch discs',
      'Heat a Kadai with oil and when the oil is hot, deep fry the discs on low flame until crispy.',
      'Drain to a kitchen towel.',
      'Have all the chutneys ready.',
      'When ready to assemble, take the serving bowl, dip the papdi into sweet curds, or pour curds over it.',
      'over this add Imli sonth chutney, pudina chutney, kala namak, and chaat masala.',
      'You can finish this off by repeating the process.',
      'Typically in the chaat shop, they also serve a Vada served in the same process.',
      'I skipped serving the papdi with vada.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'North Indian',    
    ],
    title: 'Paneer Ghee Roast',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://www.spicingyourlife.com/wp-content/uploads/2020/06/Paneer-Ghee-Roast.jpg',
    duration: 20,
    ingredients: [
      '1 cup Paneer',
      '3 tsp Ghee',
      '1/2 cup Onions Paste',
      '1/2 tsp Ginger Garlic Paste',
      'Salt to taste',
      '2 tbsp Curds / Yogurt',
      '1 tsp Red Chilli Powder',
      '1/2 tsp Coriander Powder',
      '1/4 tsp Cumin Powder',
      'A pinch Turmeric Powder',
      'A pinch Garam Masala',
      'Handful Coriander Leaves',
      '2 tbsp Water',
    ],
    steps: [
      'Heat a nonstick pan with 2 tbsp ghee and roast the paneer cubes until it turns golden. Remove to a bowl.',
      'To the same pan, add the onion paste, ginger garlic paste and cook for few minutes.',
      'When the masala is well cooked and oil comes out on the sides, which takes about 2 to 3 minutes, add all the spices along with salt.',
      'Cook on high and mix well. Add curds and 2 tbsp water and simmer till the mix is well cooked and smooth.',
      'Now, add the roasted paneer and toss well.',
      'Cook on high flame until all the masala coats the paneer well, add the remaining tbps of ghee and finely chopped coriander leaves.',
      'Serve hot.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'North Indian',
    
    ],
    title: 'Cabbage Vada',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://www.spicingyourlife.com/wp-content/uploads/2019/09/Cabbage-Vada.jpg',
    duration: 20,
    ingredients: [
      '2 cups Cabbage finely chopped',
      '1/2 cup Chana Dal / Bengal Gram',
      '3/4 cup Urad dal / Black Gram',
      '2 to 3 Green Chilies',
      '1 cup Onions finely chopped',
      '1/4 cup Coriander leaves finely chopped',
      'Handful Curry leaves',
      '1 inch Ginger',
      '1 tsp Fennel Seeds',
      'A Pinch Asafoetida / Hing',
      '1 no Green Chilli finely chopped',
      'Salt to taste',
      'Cooking Oil for deep frying',
    ],
    steps: [
      'Wash and rinse the lentils separately for at least 4 hours.',
      'Grind the Urad dal with just enough water to a fluffy batter.',
      'Grind the Chana dal to a semi coarse paste.',
      'Make a paste of ginger and 3 green chilies, finely chop one chili.',
      'Wash and finely chop the cabbage.',
      'In a wide bowl, add all the ingredients together.',
      'Heat a Kadai with oil, take a small portion of batter, flatten as you would with your regular vadas, and gently slide into the hot oil.',
      'Cook on a medium flame for the vadas to be cooked from within as well.',
      'Cook on both sides and drain with a slotted ladle onto a kitchen towel.',
      'Serve hot with chutney.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'Marathi', 
    ],
    title: 'Kothimbir Vadi',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://www.spicingyourlife.com/wp-content/uploads/2019/09/Maharashtrian-Kothimbir-Vadi.jpg',
    duration: 20,
    ingredients: [
      '1 cup Besan / Chickpea flour',
      '3/4 cup Coriander Leaves finely chopped',
      '1 cup Water',
      '1 tsp Cooking Oil',
      '1 tbsp Rice Flour',
      '1 tbsp Lemon Juice',
      '1/2 tsp Sugar',
      '1/2 tsp Ginger Paste',
      '1/2 tsp Green Chilli paste',
      '1 tsp Mustard Seeds',
      '2 tsp Sesame Seeds',
      'A Pinch Turmeric Powder',
      '1 tsp Red Chilli Powder',
      '1 tsp Coriander Powder',
      'A Pinch Asafoetida / Hing',
      '1 tsp Cumin Powder',
      'Cooking Oil for deep frying',
      'Salt to taste',
    ],
    steps: [
      'In a bowl, mix together besan, turmeric, ginger chili paste, chili powder, coriander powder, cumin powder, hing, rice flour, salt. Add enough water to make a thick batter.',
      'Whisk well to remove lumps if any.',
      'Heat a nonstick pan with oil, temper with mustard and sesame seeds.',
      'Add finely chopped coriander leaves, saute well',
      'Next, pour the batter and quickly keep stirring to cook the mix.',
      'When the batter comes together, and is well cooked, takes about 4 to 5 mins, add it to a greased plate and set it well with a ladle.',
      'Let it cool down or firm. Slice it into 2 inch squares and keep it ready.',
      'Heat a Kadai with oil and when oil, deep fry the vadi and let it cook on both sides.',
      'Drain with a slotted ladle and serve hot with green chutney.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm5',
    categories: [
      'Marathi',
    ],
    title: 'Kanda Bhaji Pav',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://www.spicingyourlife.com/wp-content/uploads/2021/04/Kanda-Bhaji-Pav.jpg',
    duration: 20,
    ingredients: [
      '1 cup Besan / Gram Flour /Senaga Pindi / Chickpea Flour / Kadalai Maavu',
      '1 cup Onions finely sliced juliennes',
      '2 nos Green Chilies finely chopped',
      '1 tsp Coriander Seeds',
      '1/4 tsp Carom Seeds / Ajwain',
      '1/4 tsp Poppy Seeds / Khus Khus',
      '1/2 tsp Red Chili Powder',
      'A Pinch Cooking Soda',
      'Salt to taste',
      'Cooking Oil for Deep Frying',
      'For Assembling Kanda Bhaji Pav',
      'Pav Buns as required',
      'Kanda Bhajiya',
      'Garlic Chutney',
      'Green Chutney',
      'Onions finely chopped',
      'Coriander Leaves',
      'Fried Green Chillies',
    ],
    steps: [
      'Dry roast the spices and grind them into a coarse powder but more on a smooth texture.',
      'Take the sliced onions in a bowl and add salt and chili powder.',
      'Rub well so that it coats the onions well. Next, add the spice powder and mix well.',
      'Now sprinkle the besan over it and mix again along with cooking soda.',
      'Sprinkle a few drops of water to get a firm thick batter.',
      'Heat the Kadai with cooking oil.',
      'When the oil becomes hot, take a big chunk of the batter and flatten it.',
      'Gently drop into hot oil and deep fry till golden on both sides.',
      'Drain using a slotted ladle.',
      'Assembling the Kanda Bhajiya Pav',
      'Slit the Pav.',
      'Apply green chutney on one side.',
      'Sprinkle garlic chutney on the other.',
      'Place the Kanda Bhajiya on one side, place the onions and coriander leaves over it.',
      'Cover with the other pav side and make the sandwich.',
      'Enjoy it with fried green chilies.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'Karnataka',
    ],
    title: 'Nuchinunde',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2020/06/How-to-make-Nuchinunde-600x900.jpg",
    duration: 20,
    ingredients: [
      '1/2 cup Toor Dal',
      '1/2 cup Chana Dal',
      'Water for Soaking',
      '1/2 cup Coconut grated',
      '2 tbsp Coriander finely chopped',
      'Few Curry Leaves Chopped',
      '1 inch Ginger finely chopped',
      '2 no Green Chilli finely chopped',
      '1 tsp Cumin Seeds / Jeera',
      'A Pinch Asafoetida / Hing',
      'Salt to taste',
    ],
    steps: [
      'Wash and soak the dals with enough water for at least 3 hours.',
      'Drain the water and take it along with chopped green chilies, ginger and grind to a coarse paste without adding water.',
      'If required just sprinkle few drops of water.',
      'Once the paste is ground, transfer to a bowl and add the chopped coriander leaves, curry leaves and grated coconut, salt, and hing.',
      'Mix everything well and make a ball, rolling in your palm, making a slightly oblong balls.',
      'Grease the idli plates with little oil, place the balls and steam the balls for 15 mins.',
      'Make sure if the idli pan with just enough water.',
      'Once done, allow the balls to cool down for 5 mins.',
      'Serve hot with Chutney',
      'I made Sambar and Coconut Chutney',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm16',
    categories: [
      'Tamilnadu',
    ],
    title: 'Mysore-Masala-Dosa',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2014/04/Karnataka-Mysore-Masala-Dosa.jpg",
    duration: 20,
    ingredients: [
      'Potatoes - 4 big / 2 cups',
      'Onions, juliennes - 2 cups',
      'Garlic, crushed - 1 tsp',
      'Ginger, grated - 1 tsp',
      'Coriander leaves handful',
      'Green chilies - 3 -4 nos',
      'Salt to taste',
      'Oil - 2 tsp',
      'Mustard seeds, Urad dal - 1 tsp',
      'Curry leaves handful',
      'Cashew nuts handful',
    ],
    steps: [
      'Grind fried gram, green chilies, and coconut to a coarse mixture.',
      'Saute the mint leaves for a couple of mins, then cool it. Once done, add to the coconut mix.',
      'Add coriander, tamarind extract, mint, and salt and grind it to a slightly coarse mixture.',
      'Temper with mustard, urad dal, and curry leaves.',
      'How to assemble the Mysore Masala Dosa',
      'Heat a tawa, grease with oil. Pour one ladleful of batter, spread as you do with your regular dosa. Sprinkle oil all over.',
      'Cover with a lid and cook in sim. Pores will be formed on the top and this should not be flipped on the other side for cooking.',
      'Once the top is cooked, spread the red chutney on the top, place a serving of Aloo masala on it and fold over.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'Kerala',
    ],
    title: 'Orotti ',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2018/09/Orotti-720x480.jpg",
    duration: 20,
    ingredients: [
      '2 cups Rice Flour',
      '1/2 cup Water hot',
      '1/2 cup Coconut grated',
      'Salt to taste',
      'Cooking Oil for cooki',
    ],
    steps: [
      'Take the water in a saucepan, and bring to a boil. Reduce the heat and add the grated coconut and salt.',
      'Gradually add the rice flour while constantly mixing with a wooden spoon. When the rice flour thickens and forms a mass, switch off. Let the mixture be covered for 5 minutes. I made only half the recipe and hence, add the hot water to the bowl with rice flour.',
      'After about 5 minutes, the mixture would be warm enough to handle with bare hands. You need to knead the dough when the mixture is warm.',
      'Continue kneading the dough till it is smooth. If required wet your palms with water while kneading to make it easier.',
      'Once the dough is smooth, pinch out equal balls and roll between your palms, then pat it down to 6 inch disc.',
      'These rotis can\'t be rolled out as regular rotis. You can use a plastic sheet to help you remove the rolled out discs.',
      'You can use a plastic sheet or wet cloth. Either way, flatten the balls and gently pat it down further using your fingers.',
      'Heat a pan and place the rolled out roti. Drizzle some cooking oil, cover with a lid and cook for about 2 minutes on one side.',
      'Flip the orotti to cook the other side for another minute or so. There will be tiny brown spots that appear on the cooked side.',
      'Remove from the pan and enjoy with any side dish.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'Kerala',
    ],
    title: 'Pazham- Varrati',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2013/03/Pazham-Varatti.jpg",
    duration: 20,
    ingredients: [
      'Kerala plantains / nenthra pazham - 1 cup pulp',
      'Sugar - 1.5 cups',
      'Ghee - 3 tbsps'
    ],
    steps: [
      'You need good quality, very ripe Kerala plantains (nenthra pazham) for this.',
      'Peel and then cut the plantains into rounds. Put it in the cooker for 2-3 whistles or Microwave it for 2 -3 mins until soft.',
      'Once cool, pulse it in a mixer',
      'Measure the pulp you have got. Transfer this to a broad kadai (non-stick makes your work easier).',
      'For every cup of pulp you have, add 1.5 cups of sugar.',
      'Add ghee little by little at regular intervals and stir every now and then until it reaches the required consistency.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'Bengali',
    ],
    title: 'Ghugani',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2021/05/Ghuguni.jpg",
    duration: 20,
    ingredients: [
      '1 cup White Peas / Yellow Peas (dried)',
      '1 medium Potato',
      '1 cup Onions finely chopped',
      '1 tsp Ginger Garlic Paste',
      '1 tsp Cumin Seeds',
      '1/2 cup Tomatoes',
      'Salt to taste',
      '1/2 tsp Turmeric Powder',
      '1/2 tsp Red Chilli Powder',
      '1/2 tsp Cumin Powder',
      '1 tsp Coriander Powder',
      '1 tsp Garam Masala',
      '2 tbsp Cooking Oil',
      '1 Green Chilli finely chopped',
      'Coriander Leaves handful',
    ],
    steps: [
      'Soak the white / yellow peas overnight or a minimum of 6 hours. When ready to pressure cook, change the water a couple of times. Take peas with enough water, add 1/4 tsp salt, pressure cook for 2 to 3 times.',
      'Peel off the potatoes and cut them into pieces. Once the pressure falls, add the chopped potatoes to the peas and pressure cook again for a whistle.',
      'While the peas and potatoes are cooling down, heat a nonstick pan with cooking oil.',
      'Add the cumin seeds, saute for two mins, then add finely chopped onions. Saute till it turns brown.',
      'Now, add ginger garlic paste and mix well. You can add 2 tbsp water for getting it cooked quickly.',
      'Add chopped tomatoes along with salt and turmeric powder.',
      'Cook for 5 to 7 mins, till you find oil coming out on the sides.',
      'Add cumin powder, coriander powder, garam masala, green chilli, red chili powder and combine well.',
      'Now, add the boiled white peas and potatoes to it. Mash some of the potatoes to thicken the gravy.',
      'Simmer and cook for 5 to 7 mins.',
      'Garnish with coriander leaves.',
      'Serve hot with Chakuli pithas.',
      'Tried this .',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'Odisha',
    ],
    title: 'Sweet Kordois',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        "https://www.spicingyourlife.com/wp-content/uploads/2013/09/Sweet-Kordois.jpg",
    duration: 20,
    ingredients: [
      'All purpose flour - 2 Cups',
      'Cooking oil - 2 tbsp',
      'Salt - 1/2 tsp',
      'A pinch of nigella seeds',
      'Hot water - 3/4 Cup',
      'Oil for deep frying',
      'For the sugar Syrup',
      'Water - 1/2 Cup',
      'Granulated Sugar  - 1 and 1/2 cups / Caster sugar  - 2 Cup*',
    ],
    steps: [
      'I added another 1/2 cup, though 1/2 of the final syrup remained.',
      'In a wide bowl, take the flour, salt, oil, nigella seeds, rub them together.',
      'Add the hot water gradually and mix with a spoon. Once it is cool enough to use your fingers, knead to form a firm, but elastic dough.',
      'Cover the dough and leave for a few minutes.',
      'Divide the dough into small marble-sized portions, shape it into balls and flatten them.',
      'Roll one into approximately 4 and a 1/2 inches in diameter. With a sharp knife, cut straight lines, making sure not to cut all the way through.',
      'From one end start to make a roll, pinching the ends to bind. Push the two ends of the shaped kordoi gently to plump the middle. Continue doing the same with the rest and keep them ready.',
      'Heat a kadai with oil.',
      'Deep fry the kordoi till crisp and place them on kitchen towels to drain the excess oil and let them cool for a few minutes.',
      'Meanwhile, make the sugar syrup by placing the sugar and water together in a thick bottomed pan over the flame. Bring to a boil. The mixture will start to foam. Remove the scum if any. And again boil.',
      'The syrup is ready when a tiny bit placed between your thumb and forefinger feels quite sticky, but is not of a thread consistency.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'Rajasthan',
    ],
    title: 'Bhedawari Puri',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl: "https://www.spicingyourlife.com/wp-content/uploads/2020/09/Rajasthani-Bhedawi-Puri-aur-Sabzi-Thali-750x1000.jpg",
    duration: 20,
    ingredients: [
      '1.5 cups All Purpose Flour / Maida',
      '2 tbsp Cooking Oil use hot oil',
      '1/2 tsp Kalonji / Nigella Seeds',
      'Salt to taste',
      'Cooking Oil for deep frying',
      '1/2 cup Urad dal',
      '1 tbsp Coriander Seeds',
      '1 tbsp Cumin seeds / Jeera',
      '1 tsp Fennel Seeds / Saunf',
      '1 tsp Peppercorn',
      '4 to 5 nos Dry Red Chilies use Kashmiri red chilies if you have',
      '2 tbsp Cooking Oil',
      'Salt to taste',
    ],
    steps: ['Take all the ingredients in a wide bowl and knead to a stiff dough. Cover and keep it aside for 10 minutes.',
'For the stuffing',
'Wash and soak the urad dal for 3 hours. Drain and coarsely grind the urad dal in a mixer without using any water. Keep aside.',
'Heat a nonstick, add the coriander seeds, cumin seeds, fennel seeds, peppercorns, red chilies, and dry roast on a medium flame for 1 to 2 minutes. Cool slightly and grind in a mixer to a fine powder. Keep aside.',
'In the same pan, add the urad dal mixture and cook on a medium flame for 2 to 3 minutes or till the urad dal turns golden brown in colour. Once the dal is cooked, add the ground powder and continue cooking for few more minutes till everything comes together. Keep aside for it to cool down. Divide into equal balls and keep it aside.',
'Making the stuffed poori',
'Take the dough and knead well again. Divide the dough into 10 equal portions.',
'Take a ball and flatten the sides, place the stuffing in the center, and enclose from all sides, make sure the stuffing is well covered.',
'Slightly flatten and dust well with flour. Gently roll out into 6 inch disc.',
'Heat a Kadai with enough oil to deep fry.',
'When the oil is hot, gently slide in the stuffed pooris and cook on both sides.',
'Drain using a slotted ladle and place on a kitchen towel to absorb excess oil.',],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm12',
    categories: [
      'Bengali',
    ],
    title: 'Roshogulla',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl: "https://www.spicingyourlife.com/wp-content/uploads/2017/09/Rasgulla-600x400.jpg",
    duration: 20,
    ingredients: ['For the Rasgullas',
'1 cup Milk / 250 ml (Full Cream Milk will be best)',
'2 tsp Lemon Juice (you may not use all of this)',
'For Sugar Syrup',
'1/2 cup Sugar',
'1 1/2 cups Water',
'2 Cardamom',],
    steps: ['Making the soft fresh Chhana to make the Rasgulla',
'Always use whole milk or full cream milk for best results.',
'I have used both lemon and fermented whey water for making the paneer / chhana.',
'If using Lemon, ensure you run the cheese in water to remove the lemon taste.',
'If using fermented whey water, dilute it and use.',
'If using vinegar, again dilute with water and use by drops.',
'Once you boil the milk, remove from fire, slowly add the curdling agent by drops, while you gently stir the milk to enhance the coagulation.',
'Do not boil the milk once you add the curdling agent, else you will end up having chewy rasgullas.',
'Once you get greenish liquid, it means all the cheese is formed.',
'Use a cheesecloth or a muslin cloth to gather the cheese.',
'Cover the vessel with the cloth and pour it over. Gather the cloth together and gently tie the mouth and let it drain. Do not press it down to drain the liquid yourself.',
'The drained chhana should be crumbly and still has some moisture. If the chhana is too dry, you won’t be able to get the balls hold the shape.',
'I left the chhana draining for 30 mins, while some advice to be left overnight, I found 30 mins worked out well for me.',
'Kneading the chhana to make the Rasgullas.',
'For all Bengali Sweets, it’s important that you knead the fresh chhana well.',
'It is even more important for sweets like the boiled Rasgullas or deep fried Pantuas types.',
'Once you have the excess whey drained, take the chhana on a plate or a board you have cleaned and pat dried. I took a wide bowl so that I could hold it with the left hand and knead with my right heel.',
'Start with rubbing the chhana with fingers to break down the cheese to further smaller size, gather again and continue this for 10 mins.',
'Then start kneading with your heel and rub forward. This again takes about 10 mins. In total I must have spent some 30 to 40 mins, kneading the chhana of about 4 liters milk each batch.',
'When you feel the kneading is enough, pinch out a ball and roll between your palm, if you notice the ball being formed without a crack and you have a sheen of oil over, it’s done.',
'The ball has to be smooth and shiny.',
'Once this is done, you can use this basic rasgulla to make different sweets like Chanar Puli, Danadar, Ras Malai, Khirkadam etc.',
'Making the Sugar Syrup for Rasgulla',
'The ratio of sugar to water is always 1:3 for a perfect sweet tasting Rasgulla. We do not want an overtly sweet ball here. However, if you want more sweet to your syrup, increase the sugar.',
'You can add spices like cardamom or cinnamon or rose water as per your taste. I used cardamon for most variety.',
'The cooking vessel for the Rasgulla',
'Rasgullas expand when it gets boiled. So always use a very wide vessel for the sugar syrup. Ensure the balls are not crowding in the pot. If this happens, the rasgullas become flat or lose its shape.',
'So make sure the pot you use to make the syrup and boil the balls are wide enough. The rasgullas double in size after getting cooked.',
'Choose a vessel with a lid that closes tightly over it.',
'Also, it is important that the balls do not come in contact with air, else it will deflate or not expand properly.',
'Shaping the Rasgullas',
'Remember that the rasgullas double after being cooked. So shape the balls accordingly. As I was making a huge batch with different recipes having different shapes, it was too cumbersome to maintain all these conditions. However, remember smaller ones tune double.',
'Boiling the Rasgullas',
'After ensuring you are using a wide vessel for boiling, make sure the pan comes to rolling boil and the sugar melts. We do not want a string syrup here, so have all your rasgullas shaped and ready by the time the water boils over.',
'When the water starts rolling boil, gently drop in the balls. Cover with lid.',
'Boil like this for 10 minutes. If the sugar-water solution is becoming thick, sprinkle some cold water on top. It should be sprinkled and not simply poured in, as that will bring the temperature down and stop the cooking process.',
'Switch off the flame, and allow to cool naturally. Don’t stir, move or touch the vessel until the Rossogollas have cooled!',
'How to test Rasgullas are cooked',
'While it is said that the balls coming in contact with air, will deflate the shape, may use the technique of dropping the balls in a cup of water. If the ball sinks, it is done. If it floats, boil for a couple of minutes and check again.',
'I simply cooked for 10 mins on high flame, left it uninterrupted for 30 mins or so.',],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm13',
    categories: [
      'Bengali',
      
    ],
    title: 'Bhejetebil Chop',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl: "https://www.spicingyourlife.com/wp-content/uploads/2019/09/Bhejetebil-Chop.jpg",
    duration: 20,
    ingredients: ['For the Bhaja Masala:',
'1/2 tsp Cumin seeds',
'1/2 tsp Fennel Seeds',
'1/2 tsp Coriander Seeds',
'6 Clove',
'3 Cardamom',
'1/2 inch Cinnamon',
'12 Peppercorn',
'2 to 3 nos Dry Red Chili',
'1 no Bay leaf',
'For the Vegetable Mash',
'2 medium Beetroot',
'2 medium Carrot',
'2 large Potato',
'1 tsp Cooking Oil',
'1 tsp Red Chili Powder',
'Salt to taste',
'A Pinch Sugar',
'1/4 cup Peanuts',
'1 inch Ginger',
'3 to 4 nos Green Chilies',
'3 tbsp All Purpose Flour',
'2 tbsp Bread Crumbs',
'Handful Coriander leaves',
'For the Coating',
'1 cup All Purpose Flour',
'1 cup Bread Crumbs',
'1 tsp Pepper Powder',
'A Pinch Salt',],
    steps: ['Bhaja Masala:',
'Dry roast the whole spices listed under the masala.',
'Allow to cool down and then grind to a fine powder.',
'Notes from the author say that we can store this powder in an air-tight jar for months.',
'We can use it to sprinkle on chutneys and make more chops.',
'Vegetable Mash',
'Wash and cube the carrot and potato, pressure cook until soft.',
'Grate the beets and keep it aside.',
'Heat a little oil in a nonstick pan',
'Roast the peanuts for few mins, remove and keep aside',
'Next, add grated ginger, finely chopped green chilis saute well.',
'Then add the grated beets and cook well. Once done add the mashed vegetables, 3 tsp of Bhaja masala, red Chili Powder, salt to taste and sugar if needed.',
'Saute until the excess water dries up and the veggies come together, leaving the sides.',
'Add finely chopped coriander leaves and roasted peanuts.',
'Adjust and add spices if needed.',
'Add the flour and bread crumbs for binding.',
'Let the mixture cool down, grease your palms and make them as croquettes or oblong or oval. I decided to make these as flattened balls as the regular cutlet shape.',
'A raisin is stuffed inside as well, so you can go ahead and do it. I skipped it.',
'For Coating & Frying',
'Make a batter with both the flour, salt, and pepper by adding water as required to make a thin batter.',
'Dip or drop the chop into the flour batter, roll well. Remove and roll it over the bread crumbs. Repeat the flour and bread crumb coating for a second time.',
'Refrigerate the croquettes/chops for an hour.',
'When ready to fry, remove and keep on the counter.',
'Heat a Kadai with oil and on medium to low flame, deep fry the chops.',
'Let it turn golden brown on all sides and remove using a slotted ladle on to a kitchen towel to drain excess oil.',],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm14',
    categories: [
      'Delhi',
    
    ],
    title: 'Masala Paratha',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl: "https://www.spicingyourlife.com/wp-content/uploads/2018/09/Masala-Paratha.jpg",
    duration: 20,
    ingredients: ['For the Dough',
'1 cup Wheat Flour',
'1 tsp Ghee',
'Salt to taste',
'1 tsp Ajwain',
'Water for kneading',
'For the Spice',
'1 tsp Red Chilli powder',
'1 / 2 tsp Cumin Powder',
'Salt to taste',
'1 tsp Ghee melted',],
    steps: ['For the dough:',
'In a bowl, take the flour, salt, ghee, ajwain and mix well.',
'Slowly add water and knead to a slightly stiff dough but soft.',
'Let it rest for 10 mins.',
'Making the Masala Paratha',
'When you are ready to make, pinch out a ball of the dough.',
'Dust well and roll out to a 9 inch circle.',
'Sprinkle red chili powder, cumin, and salt all over the rolled disc.',
'Sprinkle melted ghee and using your fingers mix well and spread out evenly.',
'Using a pizza cutter, make about 4 to 5 2 inch lines both horizontal and vertical, wherein you will end up having 2 inch squares approximately.',
'Start from the second line, and stack the rest of the pieces over it, with the spice mix facing top.',
'Continue doing until you reach the last piece. This last piece can be turned and covered.',
'Roll out to a 6 inch disc with each layer stacked on top.',
'Cook on hot tawa, sprinkle oil or ghee and cook on both sides.',
'Serve hot with your side dish of choice or just curds or munch as such!',],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'Delhi',
      
    ],
    title: 'Chole Kulcha',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl: "https://www.spicingyourlife.com/wp-content/uploads/2016/03/Chole-Kulche-_-Delhi-Street-Food-600x926.jpg",
    duration: 20,
    ingredients: ['For the Chole',
'1 & 1/2 cups Kabuli Channa / Chickpeas',
'4 cups Water or just enough to cover',
'To be ground to a smooth paste',
'1 medium Bay Leaf',
'1 Black Cardamom with the outer covering removed',
'2 Cardamom with the covering removed',
'1 inch Cinnamon',
'1/2 tsp Black Pepper',
'1 Star Anise',
'4 Cloves',
'4 tsp Coriander Powder I added whole coriander 2 tsp',
'1 tsp Cumin Powder',
'1 tsp Red Chilli Powder',
'1/2 tsp Turmeric Powder',
'4 Tomatoes',
'2 tsp Ginger fresh',
'2 Green Chillies',
'2 tbsp Coriander Leaves',
'For the Seasoning',
'2 tsp Cooking Oil',
'2 tsp Ghee',
'3/4 tsp Shah Jeera / Black Cumin Seeds',
'A pinch Asafoetida / Hing',
'Salt to taste',
'2 tsp Chat Masala',
'1 tsp Tamarind soaked in 1 cup water',
'For the Kulcha',
'4 - 5 cups All Purpose Flour',
'1 cup Water lukewarm as required',
'1 tsp Instant Yeast',
'1/2 tsp Sugar',
'1 tsp Salt',
'3/4 cup Curds / Yogurt',
'2 tbsp Cooking Oil',],
    steps: ['How to make the Chole',
'Wash and soak the chickpeas in plenty of water overnight. Change the water a couple of times and pressure cook with enough water for 3 to 4 whistles. Let the pressure fall down before removing the lid.',
'In a blender, take all the ingredients listed for paste and blend well. Put in the chopped tomatoes ginger, ginger, green chili and coriander and blend to a smooth puree without using any water.',
'In a nonstick pan, heat the cooking oil and ghee. Once the oil is hot, stir in the shahi jeera and after a few seconds, put in the asafoetida. After few minutes, add the ground paste and cook till the oil separates from the tomatoes on medium to low heat, stirring in between about 5 to 8 minutes.',
'Put in the cooked chickpeas and the cooking water and cook till the water is reduced and you get a gravy of the required consistency.',
'Stir in the chat masala and salt and turn off the heat. Garnish with fresh coriander and green chilies and serve with kulcha.',
'How to make the Kulcha',
'In a wide bowl, take the flour, instant yeast, sugar, salt and slowly add in the lukewarm water. Mix well. Knead to a soft dough.',
'Cover and let it rest for atleast an hour or till the dough doubles.',
'Once the dough doubles, punch down slowly and divide into equal parts. On a flat surface, roll the dough into a 4” or 5” circle and place it on an oiled baking tray.',
'For Baking',
'Pre-heat the oven to 200C.',
'Place the tray in the centre of the oven and bake for 5 to 7 minutes.',
'On the tawa',
'Heat a tawa and cook the kulcha on both sides till down. Douse with butter after removing.',],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
 ];
